apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: frontend-service
data:
  default.conf: |
    server {
        listen 8083;
        listen [::]:8083;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }

        location /stub_status {
            stub_status on;
            access_log off;
        }
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
