apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /home/pepsi/Desktop/Practical_Assignment_SRE/Apps_deployment/mountDatabase 
    type: DirectoryOrCreate