apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app-services
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http 