apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: app-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: my-registry-creds
      containers:
      - name: auth-service
        image: 192.168.8.24:5000/auth-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP 
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: DB_HOST
          value: postgres-service
        resources: 
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe: 
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: / 
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3