apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-egress
  namespace: app-services
spec:
  podSelector: {}    
  policyTypes:
  - Ingress
  - Egress
  ingress: [] 
  egress:
  - to:
    - ipBlock:
        cidr: 10.96.0.10/32
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
      
 