
apiVersion: v1
kind: Pod
metadata:
  name: curl-debug-tool
  namespace: app-services
spec:
  containers:
  - name: debug-tool
    image: curlimages/curl:latest 
    command: ["sleep", "3600"]
  restartPolicy: Never