# الملف الأول: بود مؤقت لاختبار الاتصال من API إلى Postgres
# File 1: Temporary pod to test connection from API to Postgres
apiVersion: v1
kind: Pod
metadata:
  name: debugger-api-to-pg
  namespace: app-services
  labels:
    app: api-service # يأخذ هوية الـ API
spec:
  containers:
  - name: debugger
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
---
# الملف الثاني: بود مؤقت لاختبار الاتصال من Auth إلى Postgres
# File 2: Temporary pod to test connection from Auth to Postgres
apiVersion: v1
kind: Pod
metadata:
  name: debugger-auth-to-pg
  namespace: app-services
  labels:
    app: auth-service # يأخذ هوية الـ Auth
spec:
  containers:
  - name: debugger
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
---
# الملف الثالث: بود مؤقت لاختبار منع الخروج من Postgres
# File 3: Temporary pod to test egress denial from Postgres
apiVersion: v1
kind: Pod
metadata:
  name: debugger-pg-egress
  namespace: app-services
  labels:
    app: postgres # يأخذ هوية الـ Postgres
spec:
  containers:
  - name: debugger
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
