{
 "title": "Application Image",
 "tags": [ "image-service" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "image-deployment" },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "ip",
    "label": "Ip",
    "query": {
     "query": "label_values(kube_pod_ips{pod=~\"image-deployment-7d56988645-qxbg6|image-deployment-7d56988645-f5ls9\"},ip)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"image-service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Image Pod Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"image-service\"}) OR on() vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Histogram Bucket",
   "type": "timeseries",
   "description": "For calculate the respond from application  ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=\"image-service\"}[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{container=\"image-service\"}[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{container=\"image-service\"}[5m])) / sum(rate(http_request_duration_seconds_count{container=\"image-service\"}[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Request Count (Image)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod, instance) (rate(http_requests_total{pod=~\"image-deployment-.*\" , code=\"200\"}[10m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Image Service - CPU Usage (per Pod)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"app-services\", pod=~\"image-deployment-.*\"}[1m]))) / 0.02 * 100\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Image Service - Memory Usage (percentage)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum by (pod) (container_memory_usage_bytes{namespace=\"app-services\", pod=~\"image-deployment-.*\"})\n)\n/ on (pod)\ngroup_left() (\n  sum by (pod) (kube_pod_container_resource_requests{namespace=\"app-services\", pod=~\"image-deployment-.*\", resource=\"memory\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}