{
 "title": "Application WebPortal",
 "tags": [
  "Frontend",
  "webportal"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"nginx-exporter\"},container)"
    }
   },
   { "name": "job", "label": "Job", "query": "webportal-deployment" },
   {
    "name": "ip",
    "label": "Ip",
    "query": {
     "query": "label_values(kube_pod_ips{namespace=~\"frontend-service\"},ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WebPortal Pod Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"webportal-service\"}) OR on() vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections Accepted (WebPortal)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{pod=~\"webportal-deployment-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Active Connections (WebPortal per/s)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_connections_active{job=\"webportal-service\"  ,pod=~\"webportal-deployment-.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WebPortal Service - CPU Usage (per Pod)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubelet\" , namespace=\"frontend-service\" , pod=~\"webportal-deployment-.*\"}[1m]))) / 0.02 * 100\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WebPortal Service - Memory Usage (percentage)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum by (pod) (container_memory_usage_bytes{namespace=\"frontend-service\" , pod=~\"webportal-deployment-.*\"})\n)\n/ on (pod)\ngroup_left() (\n  sum by (pod) (kube_pod_container_resource_requests{namespace=\"frontend-service\" , pod=~\"webportal-deployment-.*\" , resource=\"memory\"})\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}